### ISSUE TITLE
ADD Employee Fiduciary

### ISSUE THREAD

**Issue by jr751** [2factorauth/twofactorauth#4063] opened 2019-10-04 18:58 UTC
Employee Fiduciary recently started using 2 factor authentication. There website is at https://www.retirementlogin.net/efc/. They are a 401k provider. They allow a one time password to be sent to either your phone or your email address. Also, they allow you to use google authenticator instead. Also, they ask for you to answer a question about your background too. I don't know how to do a pull request. Please add it.

**Comment by Carlgo11** [comment] 2019-10-04 20:22
Hi @jr751,
when you say "one time password to be sent to [...] your phone [...]" do you mean as a phone call or SMS?

Also, could you link to documentation for setting up or using 2FA?

If no documentation is available or you can't find it, could you please add some screenshots of the 2FA setup process and/or login process?
__Remember to blur or crop out any personal information linked to you.__

You can attach the screenshots here in a comment, like this:
![screenshot](https://user-images.githubusercontent.com/3535780/62257740-32b4ef00-b407-11e9-8f35-fc7c47ad72fb.gif)

**Comment by Carlgo11** [comment] 2021-10-04 21:37
Closing as the issue is incomplete and author didn't add the requested information.

**Closed as completed by Carlgo11** 2021-10-04 21:37 UTC
Labels: add site
