### ISSUE TITLE
Search not showing logos

### ISSUE THREAD

**Issue by theel0ja** [2factorauth/twofactorauth#3160] opened 2018-04-26 17:45 UTC
[![gif](https://storage.theel0ja.info/theel0ja-img-up/ShareX/h/2018/04/ezgif-4-127b2b12d2.gif)](https://storage.theel0ja.info/theel0ja-img-up/ShareX/h/2018/04/2018-04-26_20-42-17.mp4)

**Comment by mxxcon** [comment] 2018-04-26 17:51
Telling us what browser you are using would be helpful...
Do you have HTTPS Everywhere plugin installed?

**Comment by theel0ja** [comment] 2018-04-26 18:03
Firefox 60 Beta, tested also with Microsoft Edge:

![image](https://user-images.githubusercontent.com/5832930/39323403-2f014a9e-4995-11e8-8637-dbcfe3b745f6.png)

I have HTTPS Everywhere installed on my Firefox, but not on MS Edge.

Doesn't work on Chrome Canary with no addons either, all have https://twofactorauth.org/img/placeholder.png

**Comment by mxxcon** [comment] 2018-04-26 19:26
It will probably get fixed once #3090 goes live.

**Comment by conorgil** [comment] 2018-04-30 20:12
I noticed the same thing about images loading really slowly. Maybe, the same issue.

@mxxcon it looks like #3090 is already on `gh-pages`.

**Comment by kenman345** [comment] 2018-05-01 14:32
I want to point out acceptbitcoincash/acceptbitcoincash repository opted not to port back the change from #3090 because of inconsistencies we had with our setup in most browsers. We did not inform you guys at the time due to the fact that we hide via CSS half our listings and it seemed related to that nuance that we were having issues like noted above, so we thought you were not affected by the same issue and was no point bringing it up

**Comment by kenman345** [comment] 2018-05-02 15:09
I think a fix might be that after the visible images are shown using the jQuery lazy method, that if a search gets started, you have that trigger a lazy load of the remaining images as you search.

According to the Jet.js documentation on options, you can use `didSearch` to get a callback to run after the new CSS rules are applied by Jets when its searching.

Name|Required|Description
------|----- |---- 
didSearch | Optional | Callback function that will be called right after applying new CSS rule. Provides single argument with last search phrase. 

Sample snippet:
```js
didSearch: function(search_phrase) {
  console.log(search_phrase);
}
```

This means if we add the call to jQuery Lazy there, we may get it only to load the images that appear as you search and not every image on the site that hasnt loaded yet.

**Comment by onkarshinde** [comment] 2018-12-20 19:55
I can't reproduce this issue on Firefox 64. Is it still reproducible on other browsers?

**Comment by mxxcon** [comment] 2018-12-20 23:18
For me it's still happening in firefox64. logos are missing until first scroll

**Comment by Carlgo11** [comment] 2018-12-20 23:20
Same here, Firefox 64 and Chrome 73 canary

**Closed as completed** 2019-12-14 21:12 UTC
Labels: bug
