### ISSUE TITLE
Notification when site added/site 2FA support changes?

### ISSUE THREAD

**Issue by 93-infinity** [2factorauth/twofactorauth#3603] opened 2018-12-28 09:11 UTC
Hello, apologies in advance if I'm not asking in the correct place as I'm not familiar with GitHub and the software development process

I am just a regular user and I have gone through all the supported sites using the helpful Auth List to enable 2FA on my accounts one by one. This was a time consuming process and it seems the only way for me to know if a previously unlisted site is now listed, or a listed site now supports 2FA, is to repeat this process every once in a while.

And if I wanted to see a new feature, like email notifications of 2FA updates, or something like that, the best way is to get involved and contribute the feature myself?

**Comment by beerisgood** [comment] 2018-12-28 09:16
Just follow the whole project and you get notifications in your account

**Comment by stephengroat** [comment] 2018-12-28 22:15
@93-infinity this is a dupe of #2159, so i'm closing this for now. i'm in the process of making a pr that addresses this issue, feel free to contribute on that!

**Closed as completed by stephengroat** 2018-12-28 22:15 UTC
