### ISSUE TITLE
OVH now implements 2auth

### ISSUE THREAD

**Issue by i-rme** [2factorauth/twofactorauth#1106] opened 2015-05-01 15:39 UTC
OVH now implements 2auth via SMS or GAuth

Source:
https://twitter.com/dedishops/status/591552779140861952

![image](https://cloud.githubusercontent.com/assets/6007737/7432506/0b354638-f029-11e4-870e-7d496c1721b6.png)

**Comment by Carlgo11** [comment] 2015-05-02 15:36
Is this available for all customers or region specific?

**Comment by Carlgo11** [comment] 2015-05-09 12:18
@i-rme Please answer these questions below.
1. Is this available for all customers or region specific?
2. Can you confirm that this works?
3. Are there any official documentations on this?

**Comment by corppneq** [comment] 2015-05-14 02:34
I can confirm that it works for German customers.

And: https://twitter.com/ovh/status/590450825425653760

> We've now added two-factor authentication to all OVH services! Secure your login using an app, an SMS, or both! #2FA #Security

![test](https://cloud.githubusercontent.com/assets/4342880/7625058/ade4230e-f9f2-11e4-83fb-958f363d7650.png)

**Comment by CoNfu5eD** [comment] 2015-05-14 02:35
Works for me with app. ~ Germany

**Comment by jamcat22** [comment] 2015-07-29 01:14
Closing due to #1079.

**Closed as completed by jamcat22** 2015-07-29 01:14 UTC
Labels: update site
