### ISSUE TITLE
Filter based on TOTP

### ISSUE THREAD

**Issue by simplenotezy** [2factorauth/twofactorauth#2654] opened 2017-07-24 10:15 UTC
I would like to see which sites supports TOTP

**Comment by jamcat22** [comment] 2017-07-24 10:25
Hello @simplenotezy!

Would you please be more specific about your request? Are you wanting to know specifically which sites support TOTP vs another software method such as Authy? Or are you wanting to know which websites support software forms of 2FA such as TOTP vs another type of method such as a hardware USB key?

Thanks!

**Comment by joshtriplett** [comment] 2017-10-09 01:19
I'd like this as well, so that I know which sites support which method of 2FA.

**Comment by conorgil** [comment] 2018-04-21 03:52
The main consumer 2FA methods that I am aware of are: 

* SMS
* Phone (voice)
* Email (not really 2FA, but discussion for another thread)
* Time-based One-time Passwords (TOTP), for example Google Authenticator
* Push notification, for example Google Prompt, Duo Push, Authy OneTouch, etc
* Universal 2nd Factor (U2F), most commonly USB security keys, for example Yubico

It would be really nice to more clearly differentiate between the specific methods of 2FA that a service supports because each method has different security properties that users should be aware of. Most users don't even know what 2FA is and most assume that they all provide the same level of security, which is not the case. We could create a page explaining the security tradeoffs of each 2FA method so that users can learn which methods they should prefer if they are available.

Currently, the `software` category could include both TOTP and Push and the `hardware` category could include anything from U2F security keys to smart cards to RSA fobs. It seems to me like we are most interested in consumer facing web services, so there is a relatively finite set of 2FA methods supported. I think it should be possible to expand those two categories to more specifically indicate which 2FA method the service supports.

I am happy to write a one pager explaining the security tradeoffs between the methods if people are on board with creating some educational resources. Or, we could link to external resources that cover the same topics.

This issue is related to #2148.

**Comment by nitrocode** [comment] 2018-09-07 05:00
Dupe of #521

**Comment by joshtriplett** [comment] 2018-09-07 07:09
Not quite. #521 is about adding filtering, which would certainly be useful. This bug seems more about distinguishing between TOTP-style standardized software 2FA and other less standard software-based things like site-specific apps.

**Comment by phallobst** [comment] 2020-04-13 14:30
This issue has effectively been resolved by PRs #4542 (splitting up `software`) and #4584 (search by tfa methods), so we can finally close it.

**Closed as completed by phallobst** 2020-04-13 14:30 UTC
Labels: enhancement
