### ISSUE TITLE
[Feature Request] Is it possible to have section for sites that have been newly added to the list?

### ISSUE THREAD

**Issue by QUItURNE** [2factorauth/twofactorauth#4301] opened 2019-11-11 23:04 UTC
So the user can easily identify sites they use that have recently implemented 2FA without having to check every page

**Comment by zecanard** [comment] 2019-11-14 02:32
This would be great. Right now I just watch the repository for all new tickets, and that’s definitely far from ideal.

**Comment by dsoegijono** [comment] 2020-01-22 12:09
I think this is a duplicate of #521 and #519 part of [Filtering milestone](https://github.com/2factorauth/twofactorauth/milestone/4)

**Closed as completed by dsoegijono** 2020-01-22 12:09 UTC
Labels: enhancement
