### ISSUE TITLE
Special star to use any software based authenticator?

### ISSUE THREAD

**Issue by nitrocode** [2factorauth/twofactorauth#3452] opened 2018-09-11 19:41 UTC
I've used CapitalOne in the past and they do have a software based token like the repo says but you have to download their app. I'd much rather use my authenticator than use a separate app.

Do you think for websites that don't require a particular app, that use the normal totp software based tokens, could be listed with a star or some other emoji?

**Comment by Carlgo11** [comment] 2018-09-14 00:26
Duplicate of #3222

**Closed as completed by Carlgo11** 2018-09-14 00:26 UTC
Labels: duplicate
