### ISSUE TITLE
Email Call For Action Body

### ISSUE THREAD

**Issue by pqhf5kd** [2factorauth/twofactorauth#4756] opened 2020-05-05 19:45 UTC
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the feature to be added: ###
Currently the email Call For Action button automatically fills in the subject of the new email popup. Can we also include the body of the message in a similar faction to the Twitter Call For Action.

I believe the following changes need to be made:

1. Modify line 99 of desktop-table.html and line 62 of mobile-table.html to:
`{% if website.email_address %} <a class="ui green mini button" href="mailto:{{website.email_address}}?subject={{email_subject|uri_escape}}&body={{email_body|replace:'WEBSITE',website.name}}" target="_blank"><i class="mail icon"></i> via Email</a>{% endif %}`

2. Add the new key and value to each language in languages.yml, `email_body`. I have copied the wording of the Twitter Call For Action but I'm open to suggestions for something longer.
`email_body: Security is important, @WEBSITE. We'd like it if you supported two factor auth.`

If there is support, I can create a pull request.

**Comment by phallobst** [comment] 2020-05-05 19:52
Duplicate of #4357

**Closed as completed by phallobst** 2020-05-05 19:52 UTC
Labels: duplicate, enhancement
