### ISSUE TITLE
Distinguish between full and partial software support for those that require specific apps

### ISSUE THREAD

**Issue by jasonkarns** [2factorauth/twofactorauth#4091] opened 2019-10-10 18:18 UTC
I stumbled here after learning that 1Password uses this source to drive whether or not 2FA recommendation banner is shown for a given site.

ebay technically supports a software-based token, but it requires their specific app. I don't think I'm the only one that typically reads "software based token" to mean "google authenticator/authy/duo/1password"...

It's great that the exceptions and restrictions are noted for ebay, but it still feels a bit misleading to give ebay a checkmark for software support.

Thoughts on making that field be less binary and instead of Yes/No, have a third state: "partial" or something?

related: #3162 #2067

**Comment by Carlgo11** [comment] 2019-10-10 18:52
Duplicate of #3162, #2067, #4090, #3818

**Closed as completed by Carlgo11** 2019-10-10 18:52 UTC
Labels: duplicate
