### ISSUE TITLE
Update Amazon Web Services

### ISSUE THREAD

**Issue by cuu508** [2factorauth/twofactorauth#4923] opened 2020-09-03 14:16 UTC
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the site entry to be updated: ###

* Site name - `Amazon Web Services`

* Site URL - `https://aws.amazon.com/`

* Site category - `Cloud Computing`

### Information about why the site entry should be updated: ###
**This site entry should be updated because:**
- [ ] It now supports 2FA.
- [ ] The methods of 2FA that it supports have changed.
- [ ] It has begun the process of implementing 2FA.
- [ ] It no longer supports 2FA.
- [ ] Its name has changed.
- [ ] Its documentation link has changed.
- [ ] Its Twitter username, Facebook page, and/or email address have changed.
- [ ] It fits better in a different category.
- [ ] Its logo has changed.
- [ ] It has been acquired or absorbed by another site, and the new site is eligible to be listed on twofactorauth.org.
- [x] Other (please describe below).

### Information about how the site entry should be updated: ###

Amazon Web Services apparently support only [one MFA device per account](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_enable_u2f.html#replace-u2f-mfa):

> You can have only one MFA device (virtual, U2F security key, or hardware) assigned to a user at a time. If the user loses a U2F key or needs to replace it for any reason, you must first deactivate the old U2F key. Then you can add a new MFA device for the user. 

This is fine for TOTP but an important restriction for security keys: you cannot have one main key and a second backup key.
It would be good to mention this restriction.

**Comment by ApCoder123** [comment] 2021-05-20 19:19
Closing as the issue is out of scope for the project. See #4941

**Closed as completed by ApCoder123** 2021-05-20 19:19 UTC
Labels: update site
