### ISSUE TITLE
Fidelity Investments no longer supports using hardware token

### ISSUE THREAD

**Issue by Searay27** [2factorauth/twofactorauth#4688] opened 2020-03-10 04:13 UTC
I was told by personnel at a local Fidelity branch that they supported the use of hardware tokens despite no mention of it on their web site.  However, when I called Fidelity Investments Security Center customer service with set up questions I was told they no longer support using hardware tokens.  I pressed further that I was told otherwise but the representative was emphatic.  Fidelity Investments web site indicates the basis of their multifactor authentication is Symantec's VIP Access.   VIP Access can support use of hardware tokens although only a couple of bespoke Yubico USB tokens are available (Symantec links to direct purchase through Amazon).  It looks like two other hardware tokens used to be an option (type that displays 6 digit code) but can no longer be ordered.  It appears Fidelity's 2nd factor process required the user to enter the code displayed by the key.  Whether Fidelity  couldn't or wouldn't implement a change to their validation process to accept a key supplied by a USB token is unclear but it appears Symantec discontinued supporting the use of tokens that display the code or, perhaps, deny there use going forward.  Other corporate clients of VIP Access (such as Schwab) do support the use of the USB token.

**Comment by Carlgo11** [comment] 2020-03-10 04:31
Are they also no longer supporting 2FA through SMS & Phone calls or is it just the hardware solution that they no longer use?

**Comment by zecanard** [comment] 2020-03-10 04:38
They still support SMS and phone call:

<img width="576" alt="Screenshot 2020-03-09 at 23 37 01" src="https://user-images.githubusercontent.com/25799849/76280191-06940300-625f-11ea-8cda-62a73b8e2e58.png">

**Comment by kilimar** [comment] 2020-03-10 20:14
I don't think it is a cut & dry that Fidelity no longer offers hardware token support.  I think it is more of 'the current state of Symantec VIP'.    By that I mean, Symantec/Norton sold it's enterprise business to boardcom (the chip manufacturer) in November 2019 while the consumer business has been renamed to NortonLifeLock.  I can't find any statement on which company owns where Symantec VIP but I would guess Broadcom.  Anyway, the problem is that, from Amazon.com, only 2 of the 4 tokens are available purchase.  The two available tokens are the YUBI-displayless-based USB-A sized.  The two unavailable tokens are the 6-digit display fob and "card".

Interestingly enough, a search on eBay yields someone selling (new in bulk packaging) e-trade branded Symantec VIP tokens with 6-digit display.

Also CDW is also selling hardware Symantec VIP tokens -- although, without pictures and without model numbers from Symantec, it is impossible to figure if they have displays or without displays.  Also in CDW, I also saw one or two Symantec VIP tokens sold only in qualities between 1000-9999.

A closing rambling comment... I am not totally sure why anyone would want a hardware token vs a software token.  If the arguement is that software tokens are less secure due to it not running on an isolated system that can't be hacked.... I would argue that one uses a (cheap) disconnected smartphone for software tokens. However, I would agree, there are other factors like duarbility, power (keeping it charged once a week), and size; however, carrying having 3-4 fob would equate to a smartphone in volume.  Personally, if only fob tokens were available, I would have 12 of them.  Very bulky.

**Closed as completed** 2021-10-06 16:33 UTC
Labels: update site
